app:
  domain: http://localhost:8080

springdoc:
  swagger-ui:
    enabled: true #local환경에서는 swagger-ui.html 노출이 가능

#local 환경 db 커넥션 정보
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pub_weather?useUnicode=yes&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MySQLDialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.
        default_batch_fetch_size: 100 #최적화 (LAZY(Colletcion 1:N) 조회시 IN 절에 담길 파라미터 개수)

jwt:
  issuer: pub-weather-local
  secret: ${JWT_SECRET_KEY:FNJ8uBBqLja2bbIc+pIkQ2X2JyC5ITNcfdceJSz1HlU=} # 32자 이상의 키값 필요, https://aesencryption.net/
  expire:
    minute : ${ACCESSTOKEN_EXPIRE_MINUTE:180}
    day : ${REFRESHTOKEN_EXPIRE_DAY:7}

security:
  oauth2.client:
    registration:
      kakao:
        clientId: 'KAKAO_CLIENT_ID'
        clientSecret: 'KAKAO_CLIENT_SECRET'
        clientAuthenticationMethod: post
        authorizationGrantType: authorization_code
        redirectUri: http://localhost:8080//billlog-api/api/v1/aouth2/code/kakao
        scope:
          - account_email
        clientName: Kakao

    # Provider 설정
    provider:
      kakao:
        authorizationUri: https://kauth.kakao.com/oauth/authorize?response_type=code
        tokenUri: https://kauth.kakao.com/oauth/token
        userInfoUri: https://kapi.kakao.com/v2/user/me
        userNameAttribute: id

# 공공데이터 포탈 (단기 예보, 중기 예보)
public:
  data:
    forecast:
      key : ${PUBLIC_DATA_FORECAST_KEY}
      short:
        baseUrl : http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
      medium:
        baseUrl : http://apis.data.go.kr/1360000/MidFcstInfoService

# Logging
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query의 ?에 어떤 값이 들어가는지 추적할 수 있는 설정입니다. TRACE Log에 값을 보여줍니다.